### ISSUE TITLE
Many2ManyFieldDescriptor can not set MappingDao and LinkedDao

### ISSUE THREAD

**Issue by ptnguyen111** [thecodingmachine/mvc.bce#10]
Create the field of type Many2ManyFieldDescriptor 

I try to click on MappingDao and LinkedDao to inject instances, the following error occur

( ! ) Fatal error: Uncaught exception 'ReflectionException' with message 'Class Mouf\MVC\BCE\Classes\Descriptors\DAOInterface does not exist' in D:\HusbandResource\Freelance\TheCodeMachine\source\mutual\vendor\mouf\mouf\src\Mouf\MoufManager.php on line 1321
( ! ) ReflectionException: Class Mouf\MVC\BCE\Classes\Descriptors\DAOInterface does not exist in D:\HusbandResource\Freelance\TheCodeMachine\source\mutual\vendor\mouf\mouf\src\Mouf\MoufManager.php on line 1321
Call Stack
# Time    Memory  Function    Location

1   0.0011  270656  {main}(  )  ..\get_instances_with_details.php:0
2   0.0469  4125400 Mouf\MoufManager->findInstances(  ) ..\get_instances_with_details.php:63
3   0.0470  4125944 __construct
(  )    ..\MoufManager.php:1321

**Comment by marcteyssier** [comment]
Fix
